procedimento compraCidade
inicio
escreval("+----------------------------------------+")
escreval("|==================AGRO==================|")
escreval("+----------------------+-----------------+")
escreval("|Respostas:            |Olá amigo!       |")
escreval("|                      |                 |")
escreval("|(1) Olá rapaz         |     _.---._     |")
escreval("|                      | ___/-_____-\___ |")
escreval("|(2) Não sou seu amigo |`--.._______..--´|")
escreval("|                      |     |     |     |")
escreval("|(3) vai catar coquinho|    (|O _ O|)    |")
escreval("|                      |     | ´_` |     |")
escreval("|(4) Você tem algum    |      \___/      |")
escreval("|irmão no interiornet? |    __/\ /\__    |")
escreval("|                      |   /   \V/   \   |")
escreval("|                      |  /  __ |     \  |")
escreval("|                      |  |  \/ |     |  |")
escreval("|                      |  |     |     |  |")
escreval("+----------------------+-----------------+")
leia(res1agro)
fimprocedimento

procedimento compraBoaCidade
inicio
escreval("+---------------------------------------------------+")
escreval("|========================AGRO=======================|")
escreval("+---------------------------------+-----------------+")
escreval("|Respostas:                       |O que você quer  |")
escreval("|                                 |comprar hoje?    |")
escreval("|(1) Gerador de sementes por:     |     _.---._     |")
escreval("|R$: 75,00                        | ___/-_____-\___ |")
escreval("|Função: transforma caroços de    |`--.._______..--´|")
escreval("|frutas em sementes para plantar. |     |     |     |")
escreval("|                                 |    (|^._.^|)    |")
escreval("|(2) Terra sagrada por:           |     | -_- |     |")
escreval("|R$: 50,00                        |      \___/      |")
escreval("|Função: Acelera o tempo de       |    __/\ /\__    |")
escreval("|crescimento das plantas.         |   /   \V/   \   |")
escreval("|                                 |  /  __ |     \  |")
escreval("|(3) Não comprar nada             |  |  \/ |     |  |")
escreval("|                                 |  |     |     |  |")
escreval("+---------------------------------+-----------------+")
leia(res2agro)
fimprocedimento

procedimento compraMediaCidade
inicio
escreval("+---------------------------------------------------+")
escreval("|========================AGRO=======================|")
escreval("+---------------------------------+-----------------+")
escreval("|Respostas:                       |Ok. O que você   |")
escreval("|                                 |quer comprar hoje|")
escreval("|(1) Gerador de sementes por:     |?    _.---._     |")
escreval("|R$: 100,00                       | ___/-_____-\___ |")
escreval("|Função: transforma caroços de    |`--.._______..--´|")
escreval("|frutas em sementes para plantar. |     |_   _|     |")
escreval("|                                 |    (|O _ O|)    |")
escreval("|(2) Terra sagrada por:           |     | ´_` |     |")
escreval("|R$: 75,00                        |      \___/      |")
escreval("|Função: Acelera o tempo de       |    __/\ /\__    |")
escreval("|crescimento das plantas.         |   /   \V/   \   |")
escreval("|                                 |  /  __ |     \  |")
escreval("|(3) Não comprar nada.            |  |  \/ |     |  |")
escreval("|                                 |  |     |     |  |")
escreval("+---------------------------------+-----------------+")
leia(res2agro)
fimprocedimento

procedimento compraRuimCidade
inicio
escreval("+--------------------------------+")
escreval("|==============AGRO==============|")
escreval("+--------------------------------+")
escreval("|Como é amigo?! _-_              |")
escreval("|            __/O_O\__           |")
escreval("|           `-._____.-´          |")
escreval("|              |\ /|             |")
escreval("|              |0_0|             |")
escreval("|         -_-  |___|             |")
escreval("|     --[[M98]__/|\              |")
escreval("|        / __|___|_\_____________|")
escreval("|          |                     |")
escreval("|          |                     |")
escreval("|          |                     |")
escreval("+--------------------------------+")
escreval("")
escreval("Você morreu.")
escreval("")
fimalgoritmo
fimprocedimento

procedimento compraSecretaCidade
inicio
fimprocedimento

Algoritmo "CIDADE"
// Disciplina  : Programação
// Professor   : José Ricardo Maçaneiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/12/2023
Var
// Seção de Declarações das variáveis 
res5, res1cafeteria, res3cafeteria, cafecha, precocafe, coin: inteiro
esp, comprarcafe, res2cafeteria, voltacafe: caracter
QI, qicafe: real
res1agro, res2agro, res3agro, res4agro: inteiro
Inicio
coin <- 10000
QI <- 100
// Seção de Comandos, procedimento, funções, operadores, etc...
enquanto res5 <> 7 faca
escreval("+--------------------------------------------------------------------------------------------------------------------------------+")
escreval("|  ___________                                                            ___________                                ___________ |")
escreval("|  | Panteno |                                                            |CALABRESO|                    _____       |  MOTEL  | |")
escreval("|  |_________|                                                            |_________|                   /     \      |_________| |")
escreval("|  _|_______|_                    ( )                                     _|_______|_       A          /_______\     _|_______|_ |")
escreval("|  | ___ ___ |                _____O                                      |  _   _  |      / \        /|       |\    |[][] [][]| |")
escreval("|  | |_| |_| |   ,_____,_,   '[____]                                      | [_] [_] |     /___\       _|_______|_    |[][] [][]| |")
escreval("|  | ___ ___ |   | TEA | |    ||  ||   -----------------------            |  _   _  |    /     \     /|Bujigango|\   |[][] [][]| |")
escreval("|  | |_| |_| |   |COFFE|_/  ========== |SUPERHIPERMEGAMERCADO|            | [_] [_] |   / MUSEU \    _|_________|_   |[][] [][]| |")
escreval("|  | ___ ___ |   \_____/    |  AGRO  | |      2 IRMÃOS       |            |  _   _  |  /_________\  /            \\  |[][] [][]| |")
escreval("|  | |_| |_| | ____|_|____  ========== -----------------------            | [_] [_] | /|_________|\ /| _       _ |\  |[][] [][]| |")
escreval("|  |   ___   | | _     _ |  |  ____  |  []        |        []             |   ___   |  |[ _____ ]|  ||/_\     /_\||  |[] ,_, []| |")
escreval("|  |   |.|   | |{_}___{_}|  |  |,,|  |  []  ___   |   ___  [] _         _ |   |,|   |  |[_]___[_]|  °|    ___    |°  |   |,|   | |")
escreval("|  |   | |   | |   |.|   |  |  |  |  |  []  |,|   |   |,|  [] |====H====| |   | |   |  |   |,|   |   |    |,|    |   |   | |   | |")
escreval("+--------------------------------------------------------------------------------------------------------------------------------+")
timer 250
escreval("Onde você gostaria de ir?")
escreval("(1) TEACOFFE")
escreval("(2) AGRO")
escreval("(3) MERCADO")
escreval("(4) Loja Calabreso")
escreval("(5) Museu")
escreval("(6) Bujigango")
escreval("(7) Voltar para casa")
escreval("(8) Sair do jogo")
timer 0
leia(res5)

escolha res5
caso 1
     procedimento teacoffe
     inicio
     escreval("+-------------------------------------------------------+")
     escreval("|          __       _||______________________________||_|")
     escreval("|         /  \      | ,___, | ,___, | ,___, |  ,_,_ |   |")
     escreval("|        /  |V      | |   |)| |   |]| \   /\|  | || |   |")
     escreval("|     __/___\__     | \___/ | |___| |  \_/-'|  |_|| |   |")
     escreval("|       |_ _|       |_______|_______|_______|_______|___|")
     escreval("|      (|O O|)                                          |")
     escreval("|       \___/     Olá                                   |")
     escreval("|     _.-/ \-._  /                                      |")
     escreval("|    /   \ /   \                                        |")
     escreval("|    |    V    |                                        |")
     escreval("|____|____|____|________________________________________|")
     escreval("|                                                       |")
     escreval("|                                                       |")
     escreval("|                                                       |")
     escreval("|                                                       |")
     escreval("+-------------------------------------------------------+")
     escreval("'Insira enter'")
     leia(esp)
     repita
     escreval("+-------------------------------------------------------+")
     escreval("|       __          _||______________________________||_|")
     escreval("|      /  \         |1 ____ |2,___, |3,___, |4 ,_,_ |5  |")
     escreval("|      V|  \        | /   \)| |   |]| \   /\|  | || |   |")
     escreval("|     __/___\__     | \___/ | |___| |  \_/-'|  |_|| |   |")
     escreval("|       |_ _|       |_______|_______|_______|_______|___|")
     escreval("|      (|O O|)                                          |")
     escreval("|       \___/     Qual café ou chá você quer?           |")
     escreval("|     _.-/ \-._  /                                      |")
     escreval("|    /   \ /   \                                        |")
     escreval("|    |    V    |                                        |")
     escreval("|____|____|____|________________________________________|")
     escreval("|                                                       |")
     escreval("|                                                       |")
     escreval("|                                                       |")
     escreval("|                                    Obs: 6 igual a nada|")
     escreval("+-------------------------------------------------------+")
     escreval("'Seu saldo é: ",coin,"'")
     leia(cafecha)
     escolha cafecha
     caso 1
          escreval("+-------+")
          escreval("|  ____ |")
          escreval("| /   \)|")
          escreval("| \___/ |")
          escreval("+-------+")
          escreval("Esse é o Café Circulate, tradicional e simples.")
          escreval("R$: 5,00")
          precocafe <- 5
     caso 2
          escreval("+-------+")
          escreval("| ,___, |")
          escreval("| |   |]|")
          escreval("| |___| |")
          escreval("+-------+")
          escreval("Esse é o Café Quadratilo, elegante e saboroso.")
          escreval("R$: 10,00")
          precocafe <- 10
     caso 3
          escreval("+-------+")
          escreval("| ,___, |")
          escreval("| \   /\|")
          escreval("|  \_/-'|")
          escreval("+-------+")
          escreval("Esse é o Chá Trialo, Seu interior possui 180 graus.")
          escreval("R$: 7,00")
          precocafe <- 7
     caso 4
          escreval("+-------+")
          escreval("|  ,_,_ |")
          escreval("|  | || |")
          escreval("|  |_|| |")
          escreval("+-------+")
          escreval("Esse é o Chá Retardo.")
          escreval("'A criativade do criador acabou'")
          escreval("R$: 4,00")
          precocafe <- 4
     caso 5
          repita
          escreval("+-------------------------------------------------------+")
          escreval("|=======================TEA=COFFE=======================|")
          escreval("+-------------------------------------------------------+")
          escreval("|          __       _||______________________________||_|")
          escreval("|         /  \      |1 ____ |2,___, |3,___, |4 ,_,_ |5  |")
          escreval("|        /  |V      | /   \)| |   |]| \   /\|  | || |   |")
          escreval("|     __/___\__     | \___/ | |___| |  \_/-'|  |_|| |   |")
          escreval("|       |_ _|       |_______|_______|_______|_______|___|")
          escreval("|      (|O O|)                                          |")
          escreval("|       \___/     Ahh.. esse café, ele ainda não está   |")
          escreval("|     _.-/ \-._  /100% funcional.                       |")
          escreval("|    /   \ /   \                                        |")
          escreval("|    |    V    |                                        |")
          escreval("|____|____|____|________________________________________|")
          escreval("|                                                       |")
          escreval("|                                                       |")
          escreval("|                                                       |")
          escreval("|                                                       |")
          escreval("+-------------------------------------------------------+")
          escreval("(1) Posso testar mesmo assim?")
          escreval("(2) hmmm")
          escreval("(3) AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.")
          leia(res1cafeteria)
          escolha res1cafeteria
          caso 1
               escreval("+-------------------------------------------------------+")
               escreval("|=======================TEA=COFFE=======================|")
               escreval("+-------------------------------------------------------+")
               escreval("|          __       _||______________________________||_|")
               escreval("|         /  \      |1 ____ |2,___, |3,___, |4 ,_,_ |5  |")
               escreval("|        /  |V      | /   \)| |   |]| \   /\|  | || |   |")
               escreval("|     __/___\__     | \___/ | |___| |  \_/-'|  |_|| |   |")
               escreval("|       |   |       |_______|_______|_______|_______|___|")
               escreval("|      (|O O|)                                          |")
               escreval("|       \___/     Bem, já estava procurando alguém para |")
               escreval("|     _.-/ \-._  /provar, e acho que você é a pessoa    |")
               escreval("|    /   \ /   \  perfeita pra isso.                    |")
               escreval("|    |    V    |                                        |")
               escreval("|____|____|____|________________________________________|")
               escreval("|                                                       |")
               escreval("|                                                       |")
               escreval("|                                                       |")
               escreval("|                                                       |")
               escreval("+-------------------------------------------------------+")
               escreval("'Insira enter'")
               leia(esp)
               escreval("+-------------------------------------------------------+")
               escreval("|=======================TEA=COFFE=======================|")
               escreval("+-------------------------------------------------------+")
               escreval("|          __       _||______________________________||_|")
               escreval("|         /  \      |1 ____ |2,___, |3,___, |4 ,_,_ |5  |")
               escreval("|        /  |V      | /   \)| |   |]| \   /\|  | || |   |")
               escreval("|     __/___\__     | \___/ | |___| |  \_/-'|  |_|| |   |")
               escreval("|       |   |       |_______|_______|_______|_______|___|")
               escreval("|      (|O O|)                                          |")
               escreval("|       \___/     Bom, esse café que eu vou te dar, ele |")
               escreval("|     _.-/ \-._  /se chama 'CaffeineScript', e ele      |")
               escreval("|    /   \ /   \  aumenta seu QI em até 5%              |")
               escreval("|    |    V    |  Vai querer?                           |")
               escreval("|____|____|____|________________________________________|")
               escreval("|                                                       |")
               escreval("|                                                       |")
               escreval("|                                                       |")
               escreval("|                                                       |")
               escreval("+-------------------------------------------------------+")
               escreval("s/n")
               leia(res2cafeteria)
               se res2cafeteria = "s" entao
                  timer 250
                  escreval("Você prova e começa a sentir um gosto estranho")
                  escreval("A textura inicial é fluida e viscosa, depois adquirir uma consistência mais densa com o tempo.")
                  timer 0
                  cafecha <- 10
                  qicafe <- QI * 0.05
                  QI <- qicafe
                  escreval("+",qicafe," QI")
                  senao
                       se res2cafeteria = "n" entao
                          escreval("'Tudo bem então'")
                       fimse
               fimse
          caso 2
               escreval("+-------------------------------------------------------+")
               escreval("|=======================TEA=COFFE=======================|")
               escreval("+-------------------------------------------------------+")
               escreval("|          __       _||______________________________||_|")
               escreval("|         /  \      |1 ____ |2,___, |3,___, |4 ,_,_ |5  |")
               escreval("|        /  |V      | /   \)| |   |]| \   /\|  | || |   |")
               escreval("|     __/___\__     | \___/ | |___| |  \_/-'|  |_|| |   |")
               escreval("|       |\ /|       |_______|_______|_______|_______|___|")
               escreval("|      (|O O|)                                          |")
               escreval("|       \___/     Viro vaca agora pra ficar mugindo?    |")
               escreval("|     _.-/ \-._  /                                      |")
               escreval("|    /   \ /   \                                        |")
               escreval("|    |    V    |                                        |")
               escreval("|____|____|____|________________________________________|")
               escreval("|                                                       |")
               escreval("|                                                       |")
               escreval("|                                                       |")
               escreval("|                                                       |")
               escreval("+-------------------------------------------------------+")
          caso 3
               escreval("+-------------------------------------------------------+")
               escreval("|=======================TEA=COFFE=======================|")
               escreval("+-------------------------------------------------------+")
               escreval("|          __       _||______________________________||_|")
               escreval("|         /  \      |1 ____ |2,___, |3,___, |4 ,_,_ |5  |")
               escreval("|        /  |V      | /   \)| |   |]| \   /\|  | || |   |")
               escreval("|     __/___\__     | \___/ | |___| |  \_/-'|  |_|| |   |")
               escreval("|       |_ u|       |_______|_______|_______|_______|___|")
               escreval("|      (|O O|)                                          |")
               escreval("|       \___/     Sinceramente, ache que você seria mais|")
               escreval("|     _.-/ \-._  /responsável, estava pensando em       |")
               escreval("|    /   \ /   \  em deixalo experimenta minha poçã...  |")
               escreval("|    |    V    |  CAFÉ, eu quis dizer café              |")
               escreval("|____|____|____|________________________________________|")
               escreval("|                                                       |")
               escreval("|                                                       |")
               escreval("|                                                       |")
               escreval("|                                                       |")
               escreval("+-------------------------------------------------------+")
          outrocaso
                   escreval("Inválido")
                   precocafe <- 0
                   cafecha <- 0
          fimescolha
          ate res1cafeteria = 1, 2, 3
     caso 6
          escreval("Então tá bom")
     outrocaso
              escreval("Inválido")
     fimescolha
     escolha cafecha
     caso 1, 2, 3, 4, 5
        escreval("Vai querer comprar?")
        leia(comprarcafe)
     fimescolha
     se comprarcafe = "s" entao
        coin <- coin - precocafe
        escreval("-",precocafe,",00")
        senao
             se comprarcafe = "n" entao
                cafecha <- 00
                precocafe <- 0
             fimse
     fimse
     escreval("Quer comprar mais café? s/n")
     leia(voltacafe)
     se voltacafe = "s" entao
        cafecha <- 0
        precocafe <- 0
     fimse
     se voltacafe = "n" entao
        cafecha <- 10
        precocafe <- 0
     fimse
     ate cafecha = 10
     fimprocedimento
     teacoffe
caso 2
     procedimento agrocidade
     inicio
     compraCidade
     escolha res1agro
     caso 1, 2, 3, 4
          escreva()
     outrocaso
              escreval("Inválido")
              repita
                    compraCidade
              ate res1agro = 1, 2, 3, 4
     fimescolha
     escolha res1agro
     caso 1
          repita
          compraBoaCidade
          escolha res2agro
          caso 1, 2, 3
               interrompa
          outrocaso
                   escreval("Inválido")
          fimescolha
          ate falso
     caso 2
          compraMediaCidade
          escolha res2agro
          caso 1, 2, 3
               escreva()
          outrocaso
                   escreval("Inválido")
                   repita
                         compraMediaCidade
                   ate res2agro = 1, 2, 3
          fimescolha
     caso 3
          compraRuimCidade
     caso 4

          escreval("+----------------------------------------+")
          escreval("|==================AGRO==================|")
          escreval("+----------------------+-----------------+")
          escreval("|                      |...              |")
          escreval("|                      |                 |")
          escreval("|                      |     _.---._     |")
          escreval("|                      | ___/-_____-\___ |")
          escreval("|                      |`--.._______..--´|")
          escreval("|                      |     |     |     |")
          escreval("|                      |    (|O _ O|)    |")
          escreval("|                      |     | ´_` |     |")
          escreval("|                      |      \___/      |")
          escreval("|                      |    __/\ /\__    |")
          escreval("|                      |   /   \V/   \   |")
          escreval("|                      |  /  __ |     \  |")
          escreval("|                      |  |  \/ |     |  |")
          escreval("|'insira enter'        |  |     |     |  |")
          escreval("+----------------------+-----------------+")
          leia(esp)
          repita
          escreval("+------------------------------------------+")
          escreval("|===================AGRO===================|")
          escreval("+----------------------+-------------------+")
          escreval("|(1) Morreu HAHAHAHAHAH|Você conheçeu ele!?|")
          escreval("|                      |Como ele está??    |")
          escreval("|(2) Bem               |      _.---._      |")
          escreval("|                      |  ___/-_____-\___  |")
          escreval("|(3) Ele tá bem, está  | `--.._______..--´ |")
          escreval("|trabalhando em uma    |      |     |      |")
          escreval("|agropécuaria lá no    |     (|O _ O|)     |")
          escreval("|interiornet.          |      | ´_` |      |")
          escreval("|                      |       \___/       |")
          escreval("|                      |     __/\ /\__     |")
          escreval("|                      |    /   \V/   \    |")
          escreval("|                      |   /  __ |     \   |")
          escreval("|                      |   |  \/ |     |   |")
          escreval("|                      |   |     |     |   |")
          escreval("+----------------------+-------------------+")
          leia(res3agro)
          escolha res3agro
          caso 1, 2, 3
               escreva("")
          outrocaso
                   escreval("Inválido")
          ate res3agro = 1, 2, 3
          escolha res3agro
          caso 1
               escreval("+------------------------------------------+")
               escreval("|===================AGRO===================|")
               escreval("+----------------------+-------------------+")
               escreval("|                      |Coringo            |")
               escreval("|                      |      _.---._      |")
               escreval("|                      |   .-´   |   `-.   |")
               escreval("|                      |   | \_.---._/ |   |")
               escreval("|                      |   |  \     /  |   |")
               escreval("|                      |   \._|^   ^|_./   |")
               escreval("|                      |     (|O _ O|)     |")
               escreval("|                      |      |V´_`V|      |")
               escreval("|                      |       \___/       |")
               escreval("|                      |     __/\ /\__     |")
               escreval("|                      |    /   \V/   \    |")
               escreval("|                      |   /  __ |     \   |")
               escreval("|                      |   |  \/ |     |   |")
               escreval("|                      |   |     |     |   |")
               escreval("+----------------------+-------------------+")
          caso 2
               escreval("+------------------------------------------+")
               escreval("|===================AGRO===================|")
               escreval("+----------------------+-------------------+")
               escreval("|                      |ok                 |")
               escreval("|                      |                   |")
               escreval("|                      |      _.---._      |")
               escreval("|                      |  ___/-_____-\___  |")
               escreval("|                      | `--.._______..--´ |")
               escreval("|                      |      |     |      |")
               escreval("|                      |     (|O _ O|)     |")
               escreval("|                      |      | ´_` |      |")
               escreval("|                      |       \___/       |")
               escreval("|                      |     __/\ /\__     |")
               escreval("|                      |    /   \V/   \    |")
               escreval("|                      |   /  __ |     \   |")
               escreval("|                      |   |  \/ |     |   |")
               escreval("|                      |   |     |     |   |")
               escreval("+----------------------+-------------------+")
          caso 3
               escreval("+--------------------------------------------+")
               escreval("|====================AGRO====================|")
               escreval("+----------------------+---------------------+")
               escreval("|                      |Avisa esse danadinho |")
               escreval("|                      |que ele tá me devendo|")
               escreval("|                      |       _.---._       |")
               escreval("|                      |   ___/-_____-\___   |")
               escreval("|                      |  `--.._______..--´  |")
               escreval("|                      |       |     |       |")
               escreval("|                      |      (|O _ O|)      |")
               escreval("|                      |       | ´_` |       |")
               escreval("|                      |        \___/        |")
               escreval("|                      |      __/\ /\__      |")
               escreval("|                      |     /   \V/   \     |")
               escreval("|                      |    /  __ |     \    |")
               escreval("|                      |    |  \/ |     |    |")
               escreval("|                      |    |     |     |    |")
               escreval("+----------------------+---------------------+")
          fimescolha
     outrocaso
              escreval("Inválido")
     fimescolha
     
     fimprocedimento
     agrocidade
caso 3
caso 4
caso 5
caso 6
caso 7
     escreva()
caso 8
outrocaso
fimescolha
fimenquanto
     escreval("+-----------------+")
     escreval("|Ass: João Barbosa|")
     escreval("|                 |")
     escreval("|                 |")
     escreval("|      _---_      |")
     escreval("|     /_____\     |")
     escreval("|     |\___/|     |")
     escreval("|    (|O _ O|)    |")
     escreval("|     | /_\ |     |")
     escreval("|      \___/      |")
     escreval("|    __/   \__    |")
     escreval("|   /   \ /   \   |")
     escreval("|  /     |o    \  |")
     escreval("|  |     |o    |  |")
     escreval("|  |     |o    |  |")
     escreval("+-----------------+")
Fimalgoritmo